using System;
using System.Linq;
using System.Numerics;
using System.Security.Claims;
using System.Security.Cryptography.X509Certificates;

namespace DeveloperChallengeVocalcom.src
{
    public class Program
    {
        public static void Main()
        {
            string[] wordStream = ["cold", "freeze", "wind", "snow", "chill", "chill", "storm", "frost", "hail", "blizzard", "icy", "snowstorm", "crystal", "cold", "wind", "snow"];

            string[] matrix =
            [
                "CHILLXYZABCTYWINDPLOSNOWVXYDABCDEFIUSHDJWHYVUCISNWBFHVUDHEJCUDYA",
                "XWINDQWERTYUIOPLKJHHSNOWXYZABCDEFSHAZNIYXFSGBXIYGFBIEYGXBIGFISRY",
                "ZXCVBNMASDFGHJKLQWERWINDFREEZESCSASXGFIEYBSGUFGBXSYGFBXSYGFIYBYF",
                "TYUIOPLKJHGFDSAZXCVBSNOWICESTORMAVXIDUFSHFNXIYGFGXIBYGFBIBYRGFXB",
                "MNBVCXZLKJHGFDSAPOIUFREEZESNOWBBFESUYGFXBIDYFBGDIYUGFBIYGFBCFYGF",
                "QWERTYUIOPLKJHGFDSAZICESTORMCOLDWRWUENZIEUNFXSHGIFYZMHIAEUIMIZEU",
                "POIUYTREWQLKJHGFDSAMICEFROSTWINDAXIUENZXSUFXONSUNXOUAXNHOUFHNOSU",
                "LKJHGFDSAPOIUYTREWQCSTORMSNOWZBCSGYAGBVFTWCARCDTAQPQIFPLIFUXCNUT",
                "ZXCVBNMASDFGHJKLQWERSTORMICECODETGAUQHNFCBYWOIRJSEMROCNHORUHPQOI",
                "ERTYUIOPLKJHGFDSAMNBSTORMWINDVBNJHNIUFMX9EURN8EIRUEOISOEIRIUNRTB",
                "VBNMASDFGHJKLQWERTYUWINDFREEZEYRESIQYBTDQIYWVTYQXTIYNXIIUWNBEYEU",
                "IOPLKJHGFDSAMNBVCXZLSTORMSNOWFSCBNNQMNVCBDBWYUIQWYWDDOUIWOHUWOWW",
                "COLDZXCVBNSNOW8GHJKLSNOWICEVBNRWQDQBYVQATRATVUIEYNEOUNAPMIOEMEUE",
                "ASDFGHJKLQWERTYUIOPLWINDFREEZEIGDEQPQPEIWUNQWPEYNQWEIUQWUXNEIMXX",
                "MNBVCXZLCJHGFDSAPOIUNOWCHILLVBNGREOMWNOUFNHEUNHEUHFOUHSOMEUFHNDO",
                "QWERTYUIHPLCOLDQDSACSNOWFREEZFSRGBPQUQHNUPEHUQEHQNEPEQIUXMQIJVNP",
                "POIUYTREIQLKJHGFDSAHSTORMSNOWOSUAGPQIEUPRCNOUECNOUCFHBQONXMIZUZY",
                "LKJHGFDSLNOWUYTREWQICESTORMFWUFYVHQPWRUCNYUXMUHNCKJDFIMXIJQÑQWAD",
                "ZXCVBNMADDFGHJKLQWELSNOWCHILLVHDGWIERYGBAOEIUOAOEIAJNOEUANHOAEYB",
                "ERTYUIOPLKJHGFDSAMNDWINDICESTVJHSGQBYQXNQECWMCUMCOMCRURHREBYQWGQ",
                "CHILLBLOWSNOWNOWINDSTORMFROSTAEIFHAOUFCHANOSUIFHOSJDFHNODGJHVNOI",
                "SNOWICEWINDSTORMFREEZEHAILSVIRURHVQEWUXBQYEWBUIXYICBYCGRIYBGRIWY",
                "WINDSTORMSNOWFREEZESNOWFROSTPEOWUQLXIWEQUNOWEUCRBYIEYRCGYBGRCIYR",
                "STORMSNOWICEWINDFREEZESTORMHBQHCHVNCFUHOIGEROEWUQWYBXWERIXBRIQOU",
                "ICESTORMWINDFROSTSNOWCHILLNMNWHVUWQBERYFOPQWRIUCMQPEWICRMRCPIHRT",
                "FREEZESNOWWINDICESTORMSNOWCAUWYETVYRUEYROEWIQUECNUHCVOMJGHSFXJBG",
                "WINDICESTORMFREEZEHAILSNOWFSNWBCKONKKMHBMGSDVIGSDVAEEYEAIYEEEYEI",
                "SNOWICESTORMWINDFREEZEFROSTSICYWBQEIUQNXNCUFHWEMXISJMPPREGRJGRNF",
                "CHILLSTORMWINDICEFREEZEHAILSIABCHSNORUNHRUOFAUHFHFMFHSAJMZGUHROU",
                "WINDFREEZESNOWICESTORMCHILLAAYXUAIANFUENHEUNFSPFPSIRMJFPEJTNMTME",
                "SNOWSTORMWINDICEFREEZEHAILFCNDEVWFQEIURPMICEJPRIUNRIPRREJMJTMGJB",
                "FROSTWINDICESTORMSNOWCHILLHCIUWFBWLIRMRNCEHURPHNERPUWEBGRYGNHFFT",
                "HAILSNOWICEFREEZESTORMWINDCAGCYSUWKMCHNKVDIUBGIYROUVNGVYRGRVBTIY",
                "STORMFREEZESNOWWINDICECHILCHUSJEBEQONQYQITBERFETQRFRTRFRRYGRBROU",
                "FREEZESTORMWINDICEWINDSNOWCVCBVUDWEOCUSYREUSNHFUIXODIUCHOUHNGOUG",
                "ICECHILLFROSTSTORMSNOWWINDVHUEIWWBMIRGAINYAEDAEDADAYBGIUYEAEYDBD",
                "WINDSNOWSTORMICEFREEZESNOWSGVYUWBNAEYEBEBGYFONFUFHSUHSROUHGSNRYF",
                "STORMSNOWICECHILLFROSTWINHVJSUWHWVFNSUROECUGNHGUTHCNOYGCBOSYGYOO",
                "COLDSTORMSNOWWINDFREEZESCVHWUWHNCVERTXONUREXOUGHTMOUHGODTGUNHGOX",
                "SNOWICEWINDFREEZEHAILFROSTVISHHWNVSOAUOXSURFOYBGSOZUHOUGNFOYFGZN",
                "FROSTFREEZEWINDSNOWCHILLHSIUAHFBWJSOLZFUGSORIYZGIYFSGRFYISFIOFNF",
                "STORMWINDICEFREEZESNOWCHILDHGQGEYDNZYOBYGFIZSYFGOFUFORFUHOUSFHMZ",
                "STORMSNOWICEFREEZEFROSTCHILSUCUVIOOEZYGFOGBIZOFZNIFHNFSOZUFHSOUF",
                "HAILICEFREEZESNOWWINDSTORMPAJBDHWFZBIEYAGIYBGIFVYCFGZISVYFGYFSIT",
                "SNOWICEWINDFREEZESTORMFROSTCUINUSMVUTFUVTFUTCDURCYDRUTDVUFBUBUTB",
                "CHILLSTORMWINDICEFREEZESNOCMWCQBYSNSJFVGFHRCDEAEWWACHFVJGOPPGVTT",
                "COLDSTORMSNOWFREEZEWINDFROQNDYNDIDMNJGVFGHGCFDGSXSFDAGHFDJHGFJFT",
                "STORMSNOWICEFREEZESNOWCHILPLMDNUSNOOOBYBFTFVRGDGCESRWEAZAQWEYCRI",
                "FREEZESTORMSNOWICEWINDCHILQBVYVWWUMWNHOUBGIYFVFDCEDESXAZQWERUVIT",
                "SNOWICEFROSTWINDSTORMFREEZEXNCHBSU7SUPYFYTFESVJFIGOYGVRDTESIFOOB",
                "WINDSNOWSTORMICEFREEZESNOWSGVYUWBNATYEBEBGYFONFUFHSUHSROUHGSNRYF",
                "STORMSNOWICECHILLFROSTWINHVJSUWHWVFOXUROECUGNHGUTHCNOYGCBOSYGYOS",
                "COLDSTORMSNOWWINDFREEZESCVHWUWHNCVERYXONUREXOUGHTMOUHGODTGUNHGON",
                "SNOWICEWINDFREEZEHAILFROSTVISHHWNVSMNUOXSURFOYBGSOZUHOUGNFOYFGZO",
                "FROSTFREEZEWINDSNOWCHILLHSIUAHFBWJSONZFUGSORIYZGIYFSGRFYISFIOFNW",
                "STORMWINDICEFREEZESNOWCHILDHGQGEYDNZGOBYGFIZSYFGOFUFORFUHOUSFHMZ",
                "STORMSNOWICEFREEZEFROSTCHILSUCUVIOOEZYGFOGBIZOFZNUFHNFSOZUFHSOUF",
                "HAILICEFREEZESNOWWINDSTORMPAJBDHWFZBIEYAGIYBGIFVYAFGZISVYFGYFSIY",
                "SNOWICEWINDFREEZESTORMFROSTCUVNUSMVUTFUVTFUTCDURCCDRUTDVUFBUBUTB",
                "CHILLSTORMWINDICEFREEZESNOCMWMQBYSNBJFVGFHRCDEAEWWACHFVJGOPPGVTD",
                "COLDSTORMSNOWFREEZEWINDFROQNDUNDIDMBJGVFGHGCFDGSXSFDAGHFDJHGFJFG",
                "STORMSNOWICEFREEZESNOWCHILPLMDNUSNOUOBYBFTFVRGDGCESRWEAZAQWEYCRI",
                "FREEZESTORMSNOWICEWINDCHILQBVYVWWUMJNHOUBGIYFVFDCEDESXAZQWERUVIQ",
                "SNOWICEFROSTWINDSTORMFREEZEXNCHBSU7OUPYFYTFESVJFIGOYGVRDTESIFOOB",
            ];

            /*
            string[] wordStream2 = ["cold", "wind", "snow", "chill"];

            string[] matrix2 = [
                        "abcdc",
                        "fgwio",
                        "chill",
                        "pqnsd",
                        "uvdxy"
                    ];
            */

            var wordFinder = new WordFinder(matrix);
            var tenMostRepeatedWords = wordFinder.Find(wordStream);

            if (tenMostRepeatedWords.Any())
            {
                int i = 0;
                Console.WriteLine("\nTen most repeated words in Matrix:");
                foreach (var word in tenMostRepeatedWords)
                {
                    Console.Write(i + 1 + ". " + word + " | ");
                    i++;
                }
            }
            else
            {
                Console.WriteLine("No words were found in the matrix.");
            }
        }

    }
}